line-length = 120
indent-width = 4
target-version = "py38"

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"

[lint]
extend-select = ["I001", "E501"]

# isort rules:
# I001: unsorted-imports

# pycodestyle rules:
# E501: line-too-long

# All rules available at: https://docs.astral.sh/ruff/rules/

[lint.pydocstyle]
convention = "google"